export const experiencesData = {
  2019: [
    {
      title: "Inventory System",
      description: "Simple UJIKOM application at SMK Bakti Nusantara 666.",
      //  buttonText: "View Project",
      hoverColor: "purple",
      gradientColors: ["#8b5cf6", "#ec4899", "#f97316"],
      gradientColorsSecond: ["#7c3aed", "#db2777", "#ea580c"],
      technologies: ["php", "mysql", "bootstrap"],
    },
    {
      title: "WJ Sneakers",
      description: "E-commerce application.",
      //  buttonText: "View Project",
      hoverColor: "purple",
      gradientColors: ["#3b82f6", "#06b6d4", "#14b8a6"],
      gradientColorsSecond: ["#2563eb", "#0891b2", "#0d9488"],
      technologies: ["wordpress"],
    },
    {
      title: "Yippe",
      description: "E-commerce application.",
      //  buttonText: "View Project",
      hoverColor: "purple",
      gradientColors: ["#ff69b4", "#ffd7a7", "#ffc078"],
      gradientColorsSecond: ["#ffd7a7", "#ffc078", "#ff69b4"],
      technologies: ["wordpress"],
    },
    {
      title: "Kaula",
      description: "E-commerce application.",
      //  buttonText: "View Project",
      hoverColor: "purple",
      gradientColors: ["#ffc500", "#ffd7a7", "#ffa500"],
      gradientColorsSecond: ["#ffb366", "#ffc078", "#ffd7a7"],
      technologies: ["wordpress"],
    },
  ],
  2020: [
    {
      title: "Robo Club",
      description:
        "E-commerce application. and company profile at CV. Sona Jaya Technology.",
      //  buttonText: "View Project",
      hoverColor: "purple",
      gradientColors: ["#8b5cf6", "#ec4899", "#f97316"],
      gradientColorsSecond: ["#7c3aed", "#db2777", "#ea580c"],
      technologies: ["wordpress"],
    },
    {
      title: "Timing Run System",
      description:
        "Application to detect runners' steps and heart rate when passing a sensor.",
      //  buttonText: "View Project",
      hoverColor: "blue",
      gradientColors: ["#3b82f6", "#06b6d4", "#14b8a6"],
      gradientColorsSecond: ["#2563eb", "#0891b2", "#0d9488"],
      technologies: ["php", "bootstrap", "mysql"],
    },
  ],
  2021: [
    {
      title: "BPJS Pribadi",
      description: "Application to collect BPJS data.",
      //  buttonText: "View Project",
      hoverColor: "purple",
      gradientColors: ["#8b5cf6", "#ec4899", "#f97316"],
      gradientColorsSecond: ["#7c3aed", "#db2777", "#ea580c"],
      technologies: ["php", "bootstrap", "mysql"],
    },
    {
      title: "LMS",
      description: "Application for learning management system.",
      //  buttonText: "View Project",
      hoverColor: "blue",
      gradientColors: ["#3b82f6", "#06b6d4", "#14b8a6"],
      gradientColorsSecond: ["#2563eb", "#0891b2", "#0d9488"],
      technologies: ["php", "codeigniter", "bootstrap", "mysql"],
    },
  ],
  2022: [
    {
      title: "Internal PT. Marketlab",
      description: "Application for internal PT. Marketlab Kreatif Media.",
      //  buttonText: "View Project",
      hoverColor: "purple",
      gradientColors: ["#8b5cf6", "#ec4899", "#f97316"],
      gradientColorsSecond: ["#7c3aed", "#db2777", "#ea580c"],
      technologies: ["php", "codeigniter", "mysql", "bootstrap"],
    },
    {
      title: "E-Voting STTT Bandung",
      description: "Application for STTT Bandung election.",
      //  buttonText: "View Project",
      hoverColor: "purple",
      gradientColors: ["#3b82f6", "#06b6d4", "#14b8a6"],
      gradientColorsSecond: ["#2563eb", "#0891b2", "#0d9488"],
      technologies: ["php", "codeigniter", "bootstrap", "mysql"],
    },
    {
      title: "Kuesioner CV. Tutor Permatha Center",
      description: "Application for kuesioner at CV. Tutor Permatha Center.",
      //  buttonText: "View Project",
      hoverColor: "purple",
      gradientColors: ["#ff69b4", "#ffd7a7", "#ffc078"],
      gradientColorsSecond: ["#ffd7a7", "#ffc078", "#ff69b4"],
      technologies: ["php", "codeigniter", "bootstrap", "mysql"],
    },
  ],
  2023: [
    {
      title: "Samsat Kawaluyaan",
      description: "Application for Samsat Kawaluyaan.",
      //  buttonText: "View Project",
      hoverColor: "blue",
      gradientColors: ["#8b5cf6", "#ec4899", "#f97316"],
      gradientColorsSecond: ["#7c3aed", "#db2777", "#ea580c"],
      technologies: ["php", "laravel", "mysql", "bootstrap"],
    },
    {
      title: "Point Of Sales",
      description: "Application for Point Of Sales.",
      //  buttonText: "View Project",
      hoverColor: "purple",
      gradientColors: ["#3b82f6", "#06b6d4", "#14b8a6"],
      gradientColorsSecond: ["#2563eb", "#0891b2", "#0d9488"],
      technologies: ["php", "laravel", "bootstrap", "mysql"],
    },
    {
      title: "Sistem Informasi Enrichment",
      description:
        "Application for Sistem Informasi Enrichment at STMIK AMIKBANDUNG.",
      //  buttonText: "View Project",
      hoverColor: "blue",
      gradientColors: ["#ff69b4", "#ffd7a7", "#ffc078"],
      gradientColorsSecond: ["#ffd7a7", "#ffc078", "#ff69b4"],
      technologies: ["php", "laravel", "mysql", "bootstrap"],
    },
  ],
  2024: [
    {
      title: "System Inventory",
      description:
        "Application that enables inventory management and item tracking.",
      //  buttonText: "View Project",
      hoverColor: "blue",
      gradientColors: ["#8b5cf6", "#ec4899", "#f97316"],
      gradientColorsSecond: ["#7c3aed", "#db2777", "#ea580c"],
      technologies: ["php", "laravel", "mysql", "bootstrap", "vue", "postman"],
    },
  ],
  2025: [
    {
      title: "Aliya Haven Store",
      description: "E-commerce application with payment integration.",
      //  buttonText: "View Project",
      hoverColor: "purple",
      gradientColors: ["#8b5cf6", "#ec4899", "#f97316"],
      gradientColorsSecond: ["#7c3aed", "#db2777", "#ea580c"],
      technologies: [
        "php",
        "laravel",
        "filament",
        "livewire",
        "tailwind",
        "xendit",
        "mysql",
      ],
    },
  ],
};
